export const ON_CASTING_URL = '/film/onCasting'
export const UPCOMING_URL = '/film/upComing'
export const PROVINCE_CITY_URL = '/provinceCity'
export const CINEMA_URL = '/cinema'
export const FILM_URL = '/film'
