export const ON_CASTING_URL = '/film/onCasting'
export const UPCOMING_URL = '/film/upComing'
export const PROVINCE_CITY_URL = '/provinceCity'
export const CINEMA_URL = '/cinema'
export const FILM_URL = '/film'
export const SHOW_URL = '/show'
export const SHOWS_OF_FILM = '/show/filmDetail'
export const SET_SEATS_ON_HOLD = '/seatMatrix/setOnHold'
